
POST https://localhost:1337/login
Content-Type: application/json

{
  "firstName": "Bonnie",
  "lastName": "Lass",
  "email": "bonnie.lass@mycompany.com",
  "password": "password",
  "role": "admin"
}
